# Clipboard manager history
bindsym $mod+Shift+v exec wofi-clipman

# --- Media Keys ---
# Volume Control with Notifications
bindsym XF86AudioRaiseVolume exec pamixer --increase 5 && ~/dotfiles/scripts/volume-notify.sh
bindsym XF86AudioLowerVolume exec pamixer --decrease 5 && ~/dotfiles/scripts/volume-notify.sh
bindsym XF86AudioMute exec pamixer --toggle-mute && ~/dotfiles/scripts/volume-notify.sh

# Open lock screen
bindsym $mod+Shift+x exec swaylock

bindsym Print exec ~/dotfiles/scripts/screenshot.sh

# Launch Google Chrome
bindsym $mod+Space+g exec google-chrome

# Launch Spotify
bindsym $mod+Space+m exec spotify
