set -g default-terminal "xterm-256color"
set -as terminal-overrides ",xterm-256color:Tc"
set -as terminal-overrides ",xterm-256color:RGB"

set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -sg escape-time 1

set -g base-index 1
set -g pane-base-index 1

set -g mouse off

# Reload

unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Panes

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Copy

setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Plugins

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

run '~/.tmux/plugins/tpm/tpm'

# Status & theme

set -g status-interval 60
set -g status-justify centre

set -g status-style bg=#1c1c1c,fg=#9c9c9c
set -g message-style bg=#1c1c1c,fg=#9c9c9c

set -g pane-border-style fg=#303030
set -g pane-active-border-style fg=#80a0ff

setw -g window-status-activity-style none

setw -g window-status-format "#I  #W#{?window_flags, #[fg=#e65e72]#{window_flags},}"
setw -g window-status-current-format \
"#[bg=#353946,fg=#ffffff] #I  #W #{?window_flags,#[fg=#e65e72]#{window_flags},} "

set -g status-left "#[fg=#f09479]⠶ #[fg=#80a0ff]#S #[fg=#666]• #h "

set -g status-right "%a %d %b  %H:%M"
